apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
  namespace: meditrack
  labels:
    app: aggregator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator-service
        image: us-central1-docker.pkg.dev/meditrack-457
        resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi