apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-info-deployment
  namespace: meditrack
  labels:
    app: doctor-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-info
  template:
    metadata:
      labels:
        app: doctor-info
    spec:
      containers:
      - name: doctor-info-service
        image: us-central1-docker.pkg.dev/meditrack-459