apiVersion: v1
kind: Service
metadata:
  name: doctor-info-service
  labels:
    app: doctor-info
spec:
  selector:
    app: doctor-info
  ports:
    - protocol: TCP
      port: 80       # The port the service will expose
      targetPort: 80 # The container port where the application is running
  type: LoadBalancer