apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: patient-record-srv-hpa
  namespace: meditrack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: patient-record-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 00
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85