apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
  namespace: meditrack
  labels:
    app: patient-record
spec:
  selector:
    app: patient-record
  ports:
    - protocol: TCP
      port: 80       # The port the service will expose
      targetPort: 80 # The container port where the application is running
  type: LoadBalancer