apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-srv-deployment
  namespace: meditrack
  labels:
    app: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification-service
        image: us-central1-docker.pkg.dev/healthsync-445
        resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi