apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: meditrack
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 80       # The port the service will expose
      targetPort: 80 # The container port where the application is running
  type: LoadBalancer